# Copyright 2026 Enactic, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

right:

  joint1:
    kp: 100.0
    kd: 5.25

  joint2:
    kp: 100.0
    kd: 5.0

  joint3:
    kp: 75.0
    kd: 2.0

  joint4:
    kp: 85.0
    kd: 2.0

  joint5:
    kp: 20.0
    kd: 1.0

  joint6:
    kp: 28.0
    kd: 1.75

  joint7:
    kp: 35.0
    kd: 1.75

left:

  joint1:
    kp: 100.0
    kd: 5.25

  joint2:
    kp: 100.0
    kd: 5.0

  joint3:
    kp: 75.0
    kd: 2.0

  joint4:
    kp: 85.0
    kd: 2.0

  joint5:
    kp: 20.0
    kd: 1.0

  joint6:
    kp: 28.0
    kd: 1.75

  joint7:
    kp: 35.0
    kd: 1.75

